<#--
****************************************************************************
MontiCore Language Workbench, www.monticore.de
Copyright (c) 2017, MontiCore, All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
contributors may be used to endorse or promote products derived from this
software without specific prior written permission.

This software is provided by the copyright holders and contributors
"as is" and any express or implied warranties, including, but not limited
to, the implied warranties of merchantability and fitness for a particular
purpose are disclaimed. In no event shall the copyright holder or
contributors be liable for any direct, indirect, incidental, special,
exemplary, or consequential damages (including, but not limited to,
procurement of substitute goods or services; loss of use, data, or
profits; or business interruption) however caused and on any theory of
liability, whether in contract, strict liability, or tort (including
negligence or otherwise) arising in any way out of the use of this
software, even if advised of the possibility of such damage.
****************************************************************************
-->
${tc.signature("ast", "astType")}
<#assign genHelper = glex.getGlobalVar("astHelper")>
        # generated by template ast_python.additionalmethods.Accept
<#if genHelper.isSupertypeOfHWType(astType.getName())>
<#assign plainName = genHelper.getPlainName(astType)>
        # We allow a down cast here, because the subclass ${plainName} must exist
        # and only this subclass may exist in the AST and hence, only this class may
        # be handled by a visitor. All other cases are invalid an throw an exception!
        # This decision was made during MC Sprint Review on 16.03.2015.
        if instanceof (self,${plainName}):
            _visitor.handle((${plainName}) this)
        else:
            raise Exception("0xA7010${genHelper.getGeneratedErrorCode(ast)} Only handwritten class ${plainName} is supported for the visitor")
<#else>
        _visitor.handle(self)
</#if>
