mavenUser=${user}
mavenPassword=${pass}
repo=https://nexus.se.rwth-aachen.de/content/groups/public
useLocalRepo=false
# set true or use –PshowTestOutput=true to print test output
showTestOutput=false
genTR=false
genEMF=false
genTagging=false
org.gradle.jvmargs= \
  -XX:InitialHeapSize=2g \
  -XX:MaxHeapSize=4g \
  -Dfile.encoding=UTF-8

org.gradle.parallel=true
org.gradle.caching=true
# org.gradle.caching.debug=true

# versions used
version=7.9.0-SNAPSHOT
previous_mc_version=7.8.0

cd4a_version=7.8.0
mlc_version=7.8.0
se_commons_version=7.8.0

antlr_version=4.12.0
junit_version=6.0.3
emf_compare_version=1.2.0
ecore_version=2.16.0
commons_cli_version=1.11.0
commons_lang3_version=3.20.0
commons_text_version=1.15.0
freemarker_version=2.3.34
guava_version=33.5.0-jre
shadow_plugin_version=8.3.9
spotbugs_annotations_version=4.9.3
checkerframework_version=3.54.0
