// (c) https://github.com/MontiCore/monticore
pluginManagement {
  repositories {
    mavenCentral()
    if(("true").equals(getProperty('useLocalRepo'))){
      mavenLocal()
    }
    maven {
      credentials.username = mavenUser
      credentials.password = mavenPassword
      url = repo
    }
  
    gradlePluginPortal()
  }
}
plugins {
  id 'org.gradle.toolchains.foojay-resolver-convention' version '0.9.0'
}

boolean isCi = System.getenv().containsKey("CI")

String myGetProperty(String key){
  return getProperties().get(key)
}

buildCache {
  local {
    enabled = true
  }
  remote(HttpBuildCache) {
    enabled = myGetProperty("buildCacheURL") != null
    url = ""+myGetProperty("buildCacheURL")
    allowInsecureProtocol = false
    push = isCi   // Only CI is allowed to push
    credentials {
      username = myGetProperty("buildCacheUser")
      password = myGetProperty("buildCachePassword")
    }
  }
}



rootProject.name = 'monticore'

boolean inComposite = gradle.parent != null
if (!inComposite) {
  includeBuild('monticore-generator')
}


include(':monticore-runtime')
include(':monticore-grammar')
if(("true").equals(getProperty('genEMF'))) {
  include(':monticore-runtime-emf')
  include(':monticore-grammar-emf')
}

include('monticore-libraries:stream-symbols')
include('monticore-libraries:stream-symbols-it')
include('monticore-libraries:javagen-runtime')

include(':monticore-test:monticore-grammar-it')

include(':monticore-test:it')

include(':monticore-test:01experiments')
project(':monticore-test:01experiments').projectDir = file("monticore-test/01.experiments")
// Include all 01experiments
file("monticore-test/01.experiments").eachDir { dir ->
  if (!(dir.name in ['forEmfAst']) || "true" == getProperty('genEMF')) {// Only test EMF if the flag is set
    include(':monticore-test:01experiments:' + dir.name)
  }
}

include ':monticore-test:02experiments'
project(':monticore-test:02experiments').projectDir = file("monticore-test/02.experiments")
// Include all 02experiments
file("monticore-test/02.experiments").eachDir { dir ->
  include(':monticore-test:02experiments:' + dir.name)
}

if ("true".equals(getProperty('genTR'))) { // Only test MontiTrans if the flag is set
  include ':monticore-test:montitrans'
  project(':monticore-test:montitrans').projectDir = file("monticore-test/montitrans")
  include(':monticore-test:montitrans:test-dstl-gen')
  include(':monticore-test:montitrans:test-odrules')
  include(':monticore-test:montitrans:test-generated-dstls')
}

if (!inComposite) {
  // Gradle's project substitution due to composite builds would prevent us from using the previous grammar version
  // We avoid this by using the result of the shadowed generator jar
  gradle.beforeProject { p ->
    p.configurations.configureEach {
      if (it.name == "mcTool") {
        p.dependencies {
          mcTool("de.monticore:monticore-generator:$version") {
            capabilities {
              requireCapability("de.monticore:monticore-generator-shadow")
            }
          }
        }
      }
    }
  }
}
