/* (c) https://github.com/MontiCore/monticore */

package de.monticore.assignmentexpressions._ast;


import de.monticore.assignmentexpressions._visitor.AssignmentExpressionsVisitor;
import de.monticore.expressionsbasis._ast.ASTExpression;

public interface ASTAssignmentExpression extends /* generated by template ast.AstExtendedInterfaces*/
        ASTExpression, ASTAssignmentExpressionTOP {}
