/* (c) https://github.com/MontiCore/monticore */
description = 'MontiTrans Test: DSTLGen'

def grammarsDir = "$projectDir/src/main/grammars"
def _outputDir = "$buildDir/generated-sources"

tasks.register('generateSocialNetwork', MCTask) {
  grammar = file "$grammarsDir/mc/testcases/social/SocialNetwork.mc4"
  outputDir = file _outputDir
  def uptoDate = incCheck("mc/testcases/social/SocialNetwork.mc4")
  outputs.upToDateWhen { uptoDate }
}
tasks.register('generateSocialNetworkTR', MCTask) {
  dependsOn generateSocialNetwork
  grammar = file "$_outputDir/mc/testcases/social/tr/SocialNetworkTR.mc4"
  outputDir = file _outputDir
  modelPath += file grammarsDir
  modelPath += file _outputDir
  def uptoDate = incCheck("mc/testcases/social/tr/SocialNetworkTR.mc4")
  outputs.upToDateWhen { uptoDate }
  isDSTL = true
}
tasks.register('generateStatechart', MCTask) {
  grammar = file "$grammarsDir/mc/testcases/statechart/Statechart.mc4"
  outputDir = file _outputDir
  def uptoDate = incCheck("mc/testcases/statechart/Statechart.mc4")
  outputs.upToDateWhen { uptoDate }
}
tasks.register('generateStatechartTR', MCTask) {
  dependsOn generateStatechart
  grammar = file "$_outputDir/mc/testcases/statechart/tr/StatechartTR.mc4"
  outputDir = file _outputDir
  modelPath += file grammarsDir
  modelPath += file _outputDir
  def uptoDate = incCheck("mc/testcases/statechart/tr/StatechartTR.mc4")
  outputs.upToDateWhen { uptoDate }
  isDSTL = true
}

tasks.register('generateAutomaton', MCTask) {
  grammar = file "$grammarsDir/mc/testcases/automaton/Automaton.mc4"
  outputDir = file _outputDir
  def uptoDate = incCheck("mc/testcases/automaton/Automaton.mc4")
  outputs.upToDateWhen { uptoDate }
}
tasks.register('generateAutomatonTR', MCTask) {
  dependsOn generateAutomaton
  grammar = file "$_outputDir/mc/testcases/automaton/tr/AutomatonTR.mc4"
  outputDir = file _outputDir
  modelPath += file grammarsDir
  modelPath += file _outputDir
  def uptoDate = incCheck("mc/testcases/automaton/tr/AutomatonTR.mc4")
  outputs.upToDateWhen { uptoDate }
  isDSTL = true
}

tasks.register('generatePropertiesAutomatonComponent', MCTask) {
  grammar = file "$grammarsDir/mc/testcases/DSLWithOtherPropertiesThanAutomatonComponent.mc4"
  outputDir = file _outputDir
  def uptoDate = incCheck("mc/testcases/DSLWithOtherPropertiesThanAutomatonComponent.mc4")
  outputs.upToDateWhen { uptoDate }
}
tasks.register('generatePropertiesAutomatonComponentTR', MCTask) {
  dependsOn generatePropertiesAutomatonComponent
  grammar = file "$_outputDir/mc/testcases/tr/DSLWithOtherPropertiesThanAutomatonComponentTR.mc4"
  outputDir = file _outputDir
  modelPath += file grammarsDir
  modelPath += file _outputDir
  def uptoDate = incCheck("mc/testcases/tr/DSLWithOtherPropertiesThanAutomatonComponentTR.mc4")
  outputs.upToDateWhen { uptoDate }
  isDSTL = true
}

tasks.register('generatePropertiesAutomaton', MCTask) {
  grammar = file "$grammarsDir/mc/testcases/DSLWithOtherPropertiesThanAutomaton.mc4"
  outputDir = file _outputDir
  def uptoDate = incCheck("mc/testcases/DSLWithOtherPropertiesThanAutomaton.mc4")
  outputs.upToDateWhen { uptoDate }
}
tasks.register('generatePropertiesAutomatonTR', MCTask) {
  dependsOn(generatePropertiesAutomaton, generatePropertiesAutomatonComponent, generateAutomaton)
  grammar = file "$_outputDir/mc/testcases/tr/DSLWithOtherPropertiesThanAutomatonTR.mc4"
  outputDir = file _outputDir
  modelPath += file grammarsDir
  modelPath += file _outputDir
  def uptoDate = incCheck("mc/testcases/tr/DSLWithOtherPropertiesThanAutomatonTR.mc4")
  outputs.upToDateWhen { uptoDate }
  isDSTL = true
}

tasks.register('generateGenericDSL', MCTask) {
  grammar = file "$grammarsDir/mc/testcases/GenericDSL.mc4"
  outputDir = file _outputDir
  def uptoDate = incCheck("mc/testcases/GenericDSL.mc4")
  outputs.upToDateWhen { uptoDate }
}
tasks.register('generateGenericDSLTR', MCTask) {
  dependsOn generateGenericDSL
  grammar = file "$_outputDir/mc/testcases/tr/GenericDSLTR.mc4"
  outputDir = file _outputDir
  modelPath += file grammarsDir
  modelPath += file _outputDir
  def uptoDate = incCheck("mc/testcases/tr/GenericDSLTR.mc4")
  outputs.upToDateWhen { uptoDate }
  isDSTL = true
}
tasks.register('generateExpressionDSL', MCTask) {
  grammar = file "$grammarsDir/mc/testcases/ExpressionDSL.mc4"
  outputDir = file _outputDir
  def uptoDate = incCheck("mc/testcases/ExpressionDSL.mc4")
  outputs.upToDateWhen { uptoDate }
}
tasks.register('generateExpressionDSLTR', MCTask) {
  dependsOn generateExpressionDSL
  grammar = file "$_outputDir/mc/testcases/tr/ExpressionDSLTR.mc4"
  outputDir = file _outputDir
  modelPath += file grammarsDir
  modelPath += file _outputDir
  def uptoDate = incCheck("mc/testcases/tr/ExpressionDSLTR.mc4")
  outputs.upToDateWhen { uptoDate }
  isDSTL = true
}

tasks.register('generateEmptyComponentGrammar', MCTask) {
  grammar = file "$grammarsDir/mc/testcases/EmptyComponentGrammar.mc4"
  outputDir = file _outputDir
  def uptoDate = incCheck("mc/testcases/EmptyComponentGrammar.mc4")
  outputs.upToDateWhen { uptoDate }
}
tasks.register('generateEmptyComponentGrammarTR', MCTask) {
  dependsOn generateEmptyComponentGrammar
  grammar = file "$_outputDir/mc/testcases/tr/EmptyComponentGrammarTR.mc4"
  outputDir = file _outputDir
  modelPath += file grammarsDir
  modelPath += file _outputDir
  def uptoDate = incCheck("mc/testcases/tr/EmptyComponentGrammarTR.mc4")
  outputs.upToDateWhen { uptoDate }
  isDSTL = true
  dependsOn generateEmptyComponentGrammar
}

tasks.register('generateUsingEmptyComponentGrammar', MCTask) {
  grammar = file "$grammarsDir/mc/testcases/UsingEmptyComponentGrammar.mc4"
  outputDir = file _outputDir
  def uptoDate = incCheck("mc/testcases/UsingEmptyComponentGrammar.mc4")
  outputs.upToDateWhen { uptoDate }
  dependsOn generateEmptyComponentGrammar
}
tasks.register('generateUsingEmptyComponentGrammarTR', MCTask) {
  dependsOn generateEmptyComponentGrammar
  grammar = file "$_outputDir/mc/testcases/tr/UsingEmptyComponentGrammarTR.mc4"
  outputDir = file _outputDir
  modelPath += file grammarsDir
  modelPath += file _outputDir
  def uptoDate = incCheck("mc/testcases/tr/UsingEmptyComponentGrammarTR.mc4")
  outputs.upToDateWhen { uptoDate }
  isDSTL = true
  dependsOn generateEmptyComponentGrammarTR
}

// The following explicit task dependencies are required in order to upgrade to Gradle 8+
// They are not required when using the de.monticore.generator / MCGenTask
tasks.withType(MCTask.class).configureEach {
  dependsOn(":monticore-grammar:grammarsJar")
  dependsOn(":monticore-grammar:trafoGrammarsJar")
}

compileJava {
  dependsOn project.collect { it.tasks.withType(MCTask) }
}
sourceSets {
  main.java.srcDirs += [ _outputDir ]
}
