<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Antlr" nsURI="http://Antlr/1.0" nsPrefix="Antlr">
  <eClassifiers xsi:type="ecore:EEnum"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTConceptAntlr">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AntlrParserActions" unique="false" upperBound="-1" eType="//ASTAntlrParserAction" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AntlrLexerActions" unique="false" upperBound="-1" eType="//ASTAntlrLexerAction" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAntlrParserAction">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAntlrLexerAction">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTJavaCodeExt" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
</ecore:EPackage>
