<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Grammar" nsURI="http://Grammar/1.0" nsPrefix="Grammar">
  <eClassifiers xsi:type="ecore:EEnum"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTMCGrammar">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ImportStatements" unique="false" upperBound="-1" eType="//ASTMCImportStatement" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Supergrammar" unique="false" upperBound="-1" eType="//ASTGrammarReference" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LexProds" unique="false" upperBound="-1" eType="//ASTLexProd" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ClassProds" unique="false" upperBound="-1" eType="//ASTClassProd" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EnumProds" unique="false" upperBound="-1" eType="//ASTEnumProd" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ExternalProds" unique="false" upperBound="-1" eType="//ASTExternalProd" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InterfaceProds" unique="false" upperBound="-1" eType="//ASTInterfaceProd" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AbstractProds" unique="false" upperBound="-1" eType="//ASTAbstractProd" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ASTRules" unique="false" upperBound="-1" eType="//ASTASTRule" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Concepts" unique="false" upperBound="-1" eType="//ASTConcept" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R__package" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Component">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTMCImportStatement">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ImportList" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Star">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTGrammarReference">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Names" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTGrammarOption">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FollowOptions" unique="false" upperBound="-1" eType="//ASTFollowOption" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AntlrOptions" unique="false" upperBound="-1" eType="//ASTAntlrOption" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTFollowOption">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ProdName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAntlrOption">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTStartRule">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLexProd" eSuperTypes="//ASTProd">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Alts" unique="false" upperBound="-1" eType="//ASTLexAlt" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Variable">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Fragment">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTEnumProd" eSuperTypes="//ASTProd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Constants" unique="false" upperBound="-1" eType="//ASTConstant" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTExternalProd" eSuperTypes="//ASTProd">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTInterfaceProd" eSuperTypes="//ASTParserProd">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SuperInterfaceRule" unique="false" upperBound="-1" eType="//ASTRuleReference" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ASTSuperInterface" unique="false" upperBound="-1" eType="//ASTGenericType" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAbstractProd" eSuperTypes="//ASTProd">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SuperRule" unique="false" upperBound="-1" eType="//ASTRuleReference" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SuperInterfaceRule" unique="false" upperBound="-1" eType="//ASTRuleReference" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ASTSuperClass" unique="false" upperBound="-1" eType="//ASTGenericType" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ASTSuperInterface" unique="false" upperBound="-1" eType="//ASTGenericType" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTClassProd" eSuperTypes="//ASTParserProd">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SuperRule" unique="false" upperBound="-1" eType="//ASTRuleReference" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SuperInterfaceRule" unique="false" upperBound="-1" eType="//ASTRuleReference" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ASTSuperClass" unique="false" upperBound="-1" eType="//ASTGenericType" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ASTSuperInterface" unique="false" upperBound="-1" eType="//ASTGenericType" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Alts" unique="false" upperBound="-1" eType="//ASTAlt" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTCard">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Min">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Max">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Unbounded">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTRuleReference">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAlt">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Components" unique="false" upperBound="-1" eType="//ASTRuleComponent" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RightAssoc">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTNonTerminalSeparator" eSuperTypes="//ASTRuleComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VariableName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UsageName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Separator">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PlusKeywords">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Iteration">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTBlock" eSuperTypes="//ASTRuleComponent">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Alts" unique="false" upperBound="-1" eType="//ASTAlt" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Iteration">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTOption">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OptionValues" unique="false" upperBound="-1" eType="//ASTOptionValue" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTOptionValue">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Key">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTNonTerminal" eSuperTypes="//ASTRuleComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VariableName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UsageName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ReferencedSymbol">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Iteration">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PlusKeywords">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTTerminal" eSuperTypes="//ASTRuleComponent //ASTITerminal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VariableName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UsageName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Iteration">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTConstant" eSuperTypes="//ASTITerminal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HumanName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTConstantGroup" eSuperTypes="//ASTRuleComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Constants" unique="false" upperBound="-1" eType="//ASTConstant" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VariableName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UsageName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Iteration">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTEof" eSuperTypes="//ASTRuleComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTMCAnything" eSuperTypes="//ASTRuleComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAnything" eSuperTypes="//ASTRuleComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTSemanticpredicateOrAction" eSuperTypes="//ASTRuleComponent">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Predicate">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTConcept">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTASTRule">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ASTSuperClass" unique="false" upperBound="-1" eType="//ASTGenericType" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ASTSuperInterface" unique="false" upperBound="-1" eType="//ASTGenericType" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Methods" unique="false" upperBound="-1" eType="//ASTMethod" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AttributeInASTs" unique="false" upperBound="-1" eType="//ASTAttributeInAST" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTMethod">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="MethodParameters" unique="false" upperBound="-1" eType="//ASTMethodParameter" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Exceptions" unique="false" upperBound="-1" eType="//ASTGenericType" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R__protected">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R__private">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R__public">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R__final">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R__static">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTMethodParameter">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAttributeInAST">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Unordered">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R__derived">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTGenericType">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GenericTypes" unique="false" upperBound="-1" eType="//ASTGenericType" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dimension">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Names" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLexAlt">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LexComponents" unique="false" upperBound="-1" eType="//ASTLexComponent" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLexBlock" eSuperTypes="//ASTLexComponent">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LexAlts" unique="false" upperBound="-1" eType="//ASTLexAlt" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Negate">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Iteration">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLexCharRange" eSuperTypes="//ASTLexComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LowerChar">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UpperChar">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Negate">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLexChar" eSuperTypes="//ASTLexComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R__char">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Negate">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLexString" eSuperTypes="//ASTLexComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="String">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLexActionOrPredicate" eSuperTypes="//ASTLexComponent">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Predicate">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLexNonTerminal" eSuperTypes="//ASTLexComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Variable">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLexSimpleIteration" eSuperTypes="//ASTLexComponent">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Iteration">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLexOption">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTSymbolDefinition">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SymbolKind">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTProd" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTParserProd" abstract="true" interface="true" eSuperTypes="//ASTProd"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTRuleComponent" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTITerminal" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLexComponent" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTActionExt" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTExpressionPredicateExt" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTMCConceptExt" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
</ecore:EPackage>
