<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="JavaDSL" nsURI="http://JavaDSL/1.0" nsPrefix="JavaDSL">
  <eClassifiers xsi:type="ecore:EEnum"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTCompilationUnit">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ImportDeclarations" unique="false" upperBound="-1" eType="//ASTImportDeclaration" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TypeDeclarations" unique="false" upperBound="-1" eType="//ASTTypeDeclaration" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTPackageDeclaration">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Annotations" unique="false" upperBound="-1" eType="//ASTAnnotation" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTImportDeclaration">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R__static">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="STAR">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTPrimitiveModifier" eSuperTypes="//ASTModifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Modifier">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTEmptyDeclaration" eSuperTypes="//ASTTypeDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTClassDeclaration" eSuperTypes="//ASTTypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modifiers" unique="false" upperBound="-1" eType="//ASTModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ImplementedInterfaces" unique="false" upperBound="-1" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="Types.ecore#//ASTType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTClassBody">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ClassBodyDeclarations" unique="false" upperBound="-1" eType="//ASTClassBodyDeclaration" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTInterfaceDeclaration" eSuperTypes="//ASTTypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modifiers" unique="false" upperBound="-1" eType="//ASTModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ExtendedInterfaces" unique="false" upperBound="-1" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="Types.ecore#//ASTType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTInterfaceBody">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InterfaceBodyDeclarations" unique="false" upperBound="-1" eType="//ASTInterfaceBodyDeclaration" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTEnumDeclaration" eSuperTypes="//ASTTypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modifiers" unique="false" upperBound="-1" eType="//ASTModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ImplementedInterfaces" unique="false" upperBound="-1" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="Types.ecore#//ASTType"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EnumConstantDeclarations" unique="false" upperBound="-1" eType="//ASTEnumConstantDeclaration" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTEnumConstantDeclaration">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Annotations" unique="false" upperBound="-1" eType="//ASTAnnotation" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTEnumBody">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ClassBodyDeclarations" unique="false" upperBound="-1" eType="//ASTClassBodyDeclaration" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTClassBlock" eSuperTypes="//ASTClassBodyDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R__static">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTMethodDeclaration" eSuperTypes="//ASTClassMemberDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTConstructorDeclaration" eSuperTypes="//ASTClassMemberDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modifiers" unique="false" upperBound="-1" eType="//ASTModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTFieldDeclaration" eSuperTypes="//ASTClassMemberDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modifiers" unique="false" upperBound="-1" eType="//ASTModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VariableDeclarators" unique="false" upperBound="-1" eType="//ASTVariableDeclarator" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTConstDeclaration" eSuperTypes="//ASTInterfaceMemberDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modifiers" unique="false" upperBound="-1" eType="//ASTModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConstantDeclarators" unique="false" upperBound="-1" eType="//ASTConstantDeclarator" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTConstantDeclarator">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dim" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTInterfaceMethodDeclaration" eSuperTypes="//ASTInterfaceMemberDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTMethodSignature">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modifiers" unique="false" upperBound="-1" eType="//ASTModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dim" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTThrows">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="QualifiedNames" unique="false" upperBound="-1" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="Types.ecore#//ASTQualifiedName"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTVariableDeclarator">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTDeclaratorId">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dim" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTArrayInitializer" eSuperTypes="//ASTVariableInitializer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="VariableInitializers" unique="false" upperBound="-1" eType="//ASTVariableInitializer" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTFormalParameters">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTFormalParameterListing">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FormalParameters" unique="false" upperBound="-1" eType="//ASTFormalParameter" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTFormalParameter">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PrimitiveModifiers" unique="false" upperBound="-1" eType="//ASTPrimitiveModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLastFormalParameter">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PrimitiveModifiers" unique="false" upperBound="-1" eType="//ASTPrimitiveModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAnnotation" eSuperTypes="//ASTModifier //ASTElementValue">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAnnotationPairArguments" eSuperTypes="//ASTAnnotationArguments">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ElementValuePairs" unique="false" upperBound="-1" eType="//ASTElementValuePair" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTElementValuePair">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTElementValueArrayInitializer" eSuperTypes="//ASTElementValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ElementValues" unique="false" upperBound="-1" eType="//ASTElementValue" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAnnotationTypeDeclaration" eSuperTypes="//ASTTypeDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modifiers" unique="false" upperBound="-1" eType="//ASTModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAnnotationTypeBody">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AnnotationTypeElementDeclarations" unique="false" upperBound="-1" eType="//ASTAnnotationTypeElementDeclaration" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAnnotationMethod" eSuperTypes="//ASTAnnotationTypeElementDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modifiers" unique="false" upperBound="-1" eType="//ASTModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAnnotationConstant" eSuperTypes="//ASTAnnotationTypeElementDeclaration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Modifiers" unique="false" upperBound="-1" eType="//ASTModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VariableDeclarators" unique="false" upperBound="-1" eType="//ASTVariableDeclarator" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTDefaultValue">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLocalVariableDeclarationStatement" eSuperTypes="//ASTBlockStatement">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLocalVariableDeclaration" eSuperTypes="//ASTForInit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="PrimitiveModifiers" unique="false" upperBound="-1" eType="//ASTPrimitiveModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="VariableDeclarators" unique="false" upperBound="-1" eType="//ASTVariableDeclarator" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTJavaBlock" eSuperTypes="//ASTStatement //ASTMethodBody //ASTConstructorBody //ASTFinallyBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="BlockStatements" unique="false" upperBound="-1" eType="//ASTBlockStatement" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAssertStatement" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTIfStatement" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTForStatement" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTCommonForControl" eSuperTypes="//ASTForControl">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expressions" unique="false" upperBound="-1" eType="//ASTExpression" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTForInitByExpressions" eSuperTypes="//ASTForInit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expressions" unique="false" upperBound="-1" eType="//ASTExpression" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTEnhancedForControl" eSuperTypes="//ASTForControl">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTWhileStatement" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTDoWhileStatement" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTTryStatement" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTCatchExceptionsHandler" eSuperTypes="//ASTExceptionHandler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="CatchClauses" unique="false" upperBound="-1" eType="//ASTCatchClause" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTFinallyBlockOnlyHandler" eSuperTypes="//ASTExceptionHandler">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTTryStatementWithResources" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Resources" unique="false" upperBound="-1" eType="//ASTResource" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CatchClauses" unique="false" upperBound="-1" eType="//ASTCatchClause" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTResource">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PrimitiveModifiers" unique="false" upperBound="-1" eType="//ASTPrimitiveModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTClassOrInterfaceType">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IdentifierAndTypeArguments" unique="false" upperBound="-1" eType="//ASTIdentifierAndTypeArgument" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTIdentifierAndTypeArgument">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTCatchClause">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PrimitiveModifiers" unique="false" upperBound="-1" eType="//ASTPrimitiveModifier" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTCatchType">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="QualifiedNames" unique="false" upperBound="-1" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="Types.ecore#//ASTQualifiedName"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTSwitchStatement" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SwitchBlockStatementGroups" unique="false" upperBound="-1" eType="//ASTSwitchBlockStatementGroup" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SwitchLabels" unique="false" upperBound="-1" eType="//ASTSwitchLabel" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTSynchronizedStatement" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTReturnStatement" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTThrowStatement" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTBreakStatement" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Label">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTContinueStatement" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Label">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTEmptyStatement" eSuperTypes="//ASTStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTExpressionStatement" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTLabeledStatement" eSuperTypes="//ASTStatement">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Label">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTSwitchBlockStatementGroup">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SwitchLabels" unique="false" upperBound="-1" eType="//ASTSwitchLabel" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BlockStatements" unique="false" upperBound="-1" eType="//ASTBlockStatement" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTConstantExpressionSwitchLabel" eSuperTypes="//ASTSwitchLabel">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTEnumConstantSwitchLabel" eSuperTypes="//ASTSwitchLabel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EnumConstantName">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTDefaultSwitchLabel" eSuperTypes="//ASTSwitchLabel"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTExpression" eSuperTypes="//ASTElementValue //ASTVariableInitializer">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ParameterExpression" unique="false" upperBound="-1" eType="//ASTExpression" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SuffixOp">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PrefixOp">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BooleanNot">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MultiplicativeOp">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AdditiveOp">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShiftOp">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comparison">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IdentityTest">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BinaryAndOp">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BinaryXorOp">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BinaryOrOp">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BooleanAndOp">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BooleanOrOp">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Assignment">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R__this">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTPrimaryExpression">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R__super">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R__this">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAnonymousClass" eSuperTypes="//ASTCreator">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTArrayCreator" eSuperTypes="//ASTCreator">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTArrayDimensionByInitializer" eSuperTypes="//ASTArrayDimensionSpecifier">
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dim" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTArrayDimensionByExpression" eSuperTypes="//ASTArrayDimensionSpecifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expressions" unique="false" upperBound="-1" eType="//ASTExpression" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Dim" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTCreatedName">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IdentifierAndTypeArguments" unique="false" upperBound="-1" eType="//ASTIdentifierAndTypeArgument" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTInnerCreator">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTClassCreatorRest">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTExplicitGenericInvocation">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTExplicitGenericInvocationSuffix">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTSuperSuffix">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTArguments">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Expressions" unique="false" upperBound="-1" eType="//ASTExpression" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTModifier" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTTypeDeclaration" abstract="true" interface="true" eSuperTypes="//ASTClassMemberDeclaration //ASTInterfaceMemberDeclaration //ASTAnnotationTypeElementDeclaration //ASTBlockStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTClassBodyDeclaration" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTInterfaceBodyDeclaration" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTClassMemberDeclaration" abstract="true" interface="true" eSuperTypes="//ASTClassBodyDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTMethodBody" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTConstructorBody" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTInterfaceMemberDeclaration" abstract="true" interface="true" eSuperTypes="//ASTInterfaceBodyDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTVariableInitializer" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAnnotationArguments" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTElementValue" abstract="true" interface="true" eSuperTypes="//ASTAnnotationArguments"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAnnotationTypeElementDeclaration" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTBlockStatement" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTStatement" abstract="true" interface="true" eSuperTypes="//ASTBlockStatement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTForControl" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTForInit" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTExceptionHandler" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTFinallyBlock" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTSwitchLabel" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTCreator" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTArrayDimensionSpecifier" abstract="true" interface="true">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
  </eClassifiers>
</ecore:EPackage>
