/* (c) https://github.com/MontiCore/monticore */

plugins {
  id 'groovy'
  id 'java-gradle-plugin'
  id 'maven-publish'
  id 'com.github.johnrengelman.shadow' version '6.0.0' apply false
}

if(hasProperty('bootstrap')) {
  apply plugin: 'com.github.johnrengelman.shadow'
}

dependencies {
  if(!hasProperty('bootstrap')){
    implementation gradleApi()
    implementation localGroovy()
  } else {
    shadow gradleApi()
    shadow localGroovy()
  }
  
  implementation project(":monticore-generator")
  implementation project(":monticore-cli")
  implementation 'de.se_rwth.commons:se-commons-groovy:' + se_commons_version
}

if(hasProperty('bootstrap')) {
  shadowJar {
    classifier = ''
    zip64 true
  }
}

gradlePlugin.plugins {
  monticore {
    if(!hasProperty('bootstrap')) {
      id = 'monticore'
    } else {
      id = 'monticore-bs'
    }
    implementationClass = 'de.monticore.MCPlugin'
  }
}

if(hasProperty('bootstrap')) {
// configure deployment
  publishing {
    // configure what artifacts to publish
    publications {
      shadow(MavenPublication) { publication ->
        project.shadow.component(publication)
      }
    }
  }
}