/* generated from model TestCD4Analysis */
/* generated by template core.Class*/

/* (c) https://github.com/MontiCore/monticore */
package mc.testcd4analysis._symboltable;

import de.monticore.symboltable.serialization.json.JsonObject;


public class CDFieldSymbolDeSer extends CDFieldSymbolDeSerTOP {

  @Override
  protected void serializeType(CDTypeSymbolSurrogate type, TestCD4AnalysisSymbols2Json s2j) {

  }

  @Override
  protected CDTypeSymbolSurrogate deserializeType(JsonObject symbolJson) {
    return null;
  }
}
