/* generated from model TestCD4Analysis */
/* generated by template core.Class*/

/* (c) https://github.com/MontiCore/monticore */
package mc.testcd4analysis._symboltable;

import de.monticore.symboltable.serialization.json.JsonObject;

import java.util.List;
import java.util.Optional;


public class CDTypeSymbolDeSer extends CDTypeSymbolDeSerTOP {


  @Override
  protected void serializeCdInterfaces(List<CDTypeSymbolSurrogate> cdInterfaces, TestCD4AnalysisSymbols2Json s2j) {

  }

  @Override
  protected void serializeSuperClass(Optional<CDTypeSymbolSurrogate> superClass, TestCD4AnalysisSymbols2Json s2j) {

  }

  @Override
  protected List<CDTypeSymbolSurrogate> deserializeCdInterfaces(JsonObject symbolJson) {
    return null;
  }

  @Override
  protected Optional<CDTypeSymbolSurrogate> deserializeSuperClass(JsonObject symbolJson) {
    return Optional.empty();
  }

}
