/* generated by template symboltable.ScopeBuilder*/



package de.monticore.grammar.grammar._symboltable;

import de.monticore.grammar.grammar._symboltable.GrammarScope;

import java.util.Optional;

/**
  * Builder for {@link GrammarScope}.
  */

public class GrammarScopeBuilder {

protected GrammarScopeBuilder() {}

public GrammarScope build() {
  return new GrammarScope();
}
}