/* (c) https://github.com/MontiCore/monticore */

package de.monticore.shiftexpressions._ast;


import de.monticore.expressionsbasis._ast.ASTExpression;

public interface ASTShiftExpression extends /* generated by template ast.AstExtendedInterfaces*/
        ASTExpression, ASTShiftExpressionTOP {}
