/* (c) https://github.com/MontiCore/monticore */
plugins {
  id "jacoco"
  id "de.monticore.generator-withtr" apply false
}

description = 'MontiCore-MontiTrans Integration Test'

ext.junit_version = '5.10.3'


sonarqube {
  skipProject = true
}

subprojects {
  apply plugin: 'de.monticore.generator-withtr'
  apply plugin: 'jacoco'


  configurations.trafoGrammarSymbolDependencies.extendsFrom(configurations.grammarSymbolDependencies)

  dependencies {
    // project-dependencies using trafos are not properly working
    grammarSymbolDependencies (project(path: ":monticore-grammar", configuration: "grammarSymbolOutElements"))
    implementation (project(path: ":monticore-grammar"))

    trafoGrammarSymbolDependencies(project(path: ":monticore-grammar", configuration: "trafoGrammarSymbolOutElements"))
    trafoImplementation(project(path: ":monticore-grammar", configuration: "trafoCompileClasspathForLegacyCompat"))
    trafoImplementation files(project(":monticore-grammar").sourceSets.trafo.output.classesDirs)



    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:$junit_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_platform_version"
  }

  java {
    toolchain {
      languageVersion = JavaLanguageVersion.of(11)
    }
  }

  test {
    useJUnitPlatform()
  }
}

jar.enabled = false
sourcesJar.enabled = false
