/* generated by template symboltable.Scope*/





package de.monticore.symboltable.mocks.languages.automaton;

import java.util.Optional;

import de.monticore.symboltable.MutableScope;
import de.monticore.symboltable.mocks.languages.statechart.StateSymbol;

public class AutomatonScope  extends de.monticore.symboltable.CommonScope   {

  public AutomatonScope() {
    super();
  }

  public AutomatonScope(boolean isShadowingScope) {
    super(isShadowingScope);
  }

  public AutomatonScope(Optional<MutableScope> enclosingScope) {
    super(enclosingScope, true);
  }
  
  public Optional<AutSymbol> resolveAut(String name) {
    return resolve(name, AutSymbol.KIND);
  }
  
  public Optional<StateSymbol> resolveState(String name) {
    return resolve(name, StateSymbol.KIND);
  }
  
  
}
