/* (c) https://github.com/MontiCore/monticore */
description = 'MontiTrans Test: ODRules'

def modelsDir = "$projectDir/src/main/models"
def _outputDir = "$buildDir/generated-sources/trafogen"

dependencies {
  grammar project(':monticore-test:montitrans:test-dstl-gen')
}

tasks.register('generateMTOD') {
  group = "montitrans"
}

import de.monticore.MontiTransExec
import de.monticore.gradle.gen.MCGenTask

fileTree(dir: "$modelsDir/automaton", include: '*.mtod').each {
  def g = it
  def taskname = "generateAutomatonTRRule${it.getName().substring(0, it.getName().lastIndexOf('.'))}"
  tasks.register(taskname, MontiTransExec) {
    group = "montitrans"
    getClassPath().setFrom(project(':monticore-test:montitrans:test-dstl-gen').sourceSets.trafo.runtimeClasspath)
    TFGenTool = 'de.monticore.tf.odrules.ODRulesCLI'
    input = file(g)
    outputDir = file(_outputDir)
  }
  generateMTOD.dependsOn("$taskname")
}
fileTree(dir: "$modelsDir/misc", include: '*.mtod').each {
  def g = it
  def taskname = "generateMiscTRRules${it.getName().substring(0, it.getName().lastIndexOf('.'))}"
  tasks.register(taskname, MontiTransExec) {
    getClassPath().setFrom(project(':monticore-test:montitrans:test-dstl-gen').sourceSets.trafo.runtimeClasspath)
    TFGenTool = 'de.monticore.tf.odrules.ODRulesCLI'
    input = file(g)
    outputDir = file(_outputDir)
  }
  generateMTOD.dependsOn("$taskname")
}
tasks.register('generatePetrinetTRRules') {
  group = "montitrans"
}
fileTree(dir: "$modelsDir/petrinet", include: '**/**.mtod').each {
  def g = it
  def taskname = "generatePetrinetTRRules${it.getName().substring(0, it.getName().lastIndexOf('.'))}"
  tasks.register(taskname, MontiTransExec) {
    getClassPath().setFrom(project(':monticore-test:montitrans:test-dstl-gen').sourceSets.trafo.runtimeClasspath)
    TFGenTool = 'de.monticore.tf.odrules.ODRulesCLI'
    input = file(g)
    outputDir = file(_outputDir)
  }
  generateMTOD.dependsOn("$taskname")
}

compileJava {
  dependsOn "generateMTOD"
}

sourceSets {
  main.java.srcDirs += [ _outputDir ]
}
// As we add the MontiTrans output as a main java output, we have to add this crude dependsOn
tasks.named("generateMCGrammars", MCGenTask) {
    handWrittenCodeDir.setFrom(["empty_path"]) // Disable handwritten
}
