/* (c) https://github.com/MontiCore/monticore */

/* generated from model Tagging1*/
/* generated by template ast.AstClass*/

package mc.feature.hwc.tagging1._ast;

/* generated by template ast_emf.AstEImports*/


import java.util.List;

import mc.grammar.types.ittesttypes._ast.ASTImportStatement;
import mc.grammar.types.ittesttypes._ast.ASTQualifiedName;

public  class ASTTaggingUnit extends ASTTaggingUnitTOP
{

  private String name;

  public ASTTaggingUnit() {
    super();
  }

  public ASTTaggingUnit(List<String> r__package, List<ASTImportStatement> importStatements,
      List<ASTQualifiedName> qualifiedNames, ASTTagBody tagBody) {
    super(r__package, importStatements, qualifiedNames, tagBody);
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }
}
