/* (c) https://github.com/MontiCore/monticore */

/* generated from model null*/
/* generated by template ast.AstInterface*/



package mc.feature.hwc.tagging1._ast;

import mc.feature.hwc.tagging1._ast.ASTTagTOP;

/* generated by template ast.AstInterfaceContent*/

public interface ASTTag extends ASTTagTOP {
  String getName();
 String getTagKind();
  
}


