/* (c) https://github.com/MontiCore/monticore */

/* generated from model null*/
/* generated by template symboltable.ModelLoader*/




package mc.embedding.transitive.transcomposite._symboltable;

import de.monticore.symboltable.ArtifactScope;
import de.monticore.symboltable.MutableScope;
import de.monticore.symboltable.ResolvingConfiguration;
import de.monticore.symboltable.Scope;
import de.se_rwth.commons.logging.Log;
import mc.embedding.composite._symboltable.CompositeModelLoader;
import mc.embedding.transitive.transhost._ast.ASTTransStart;

public class TransCompositeModelLoader extends de.monticore.modelloader.ModelingLanguageModelLoader<ASTTransStart> {

  public TransCompositeModelLoader(TransCompositeLanguage language) {
    super(language);
  }

  @Override
  protected void createSymbolTableFromAST(final ASTTransStart ast, final String modelName,
    final MutableScope enclosingScope, final ResolvingConfiguration resolvingConfiguration) {
    
    final TransCompositeSymbolTableCreator symbolTableCreator =
        getModelingLanguage().getSymbolTableCreator(resolvingConfiguration, enclosingScope).orElse(null);

    if (symbolTableCreator != null) {
      Log.debug("Start creation of symbol table for model \"" + modelName + "\".",
          CompositeModelLoader.class.getSimpleName());
      final Scope scope = symbolTableCreator.createFromAST(ast);

      if (!(scope instanceof ArtifactScope)) {
        Log.warn("Top scope of model " + modelName + " is expected to be an artifact scope, but"
            + " is scope \"" + scope.getName() + "\"");
      }

      Log.debug("Created symbol table for model \"" + modelName + "\".", CompositeModelLoader.class.getSimpleName());
    }
    else {
      Log.warn("No symbol created, because '" + getModelingLanguage().getName()
          + "' does not define a symbol table creator.");
    }
  }

  @Override
  public TransCompositeLanguage getModelingLanguage() {
    return (TransCompositeLanguage) super.getModelingLanguage();
  }
}
