/* (c) https://github.com/MontiCore/monticore */

/* generated from model null*/
/* generated by template symboltable.ModelingLanguage*/




package mc.embedding.transitive.transcomposite._symboltable;

import mc.embedding.transitive.transcomposite._parser.TransCompositeParser;
import mc.embedding.transitive.transhost._symboltable.TransHostLanguage;

public class TransCompositeLanguage extends TransCompositeLanguageTOP {

  public TransCompositeLanguage() {
    super("Trans Composite Language", TransHostLanguage.FILE_ENDING);

  }

  @Override
  public TransCompositeParser getParser() {
    return new TransCompositeParser();
  }


  @Override
  public TransCompositeModelLoader getModelLoader() {
    return (TransCompositeModelLoader) super.getModelLoader();
  }

  @Override
  protected TransCompositeModelLoader provideModelLoader() {
    return new TransCompositeModelLoader(this);
  }
}
