/* (c) https://github.com/MontiCore/monticore */

package de.monticore.commonexpressions._ast;


import de.monticore.assignmentexpressions._ast.ASTAssignmentExpressionTOP;
import de.monticore.expressionsbasis._ast.ASTExpression;

public interface ASTInfixExpression extends /* generated by template ast.AstExtendedInterfaces*/
        ASTExpression, ASTInfixExpressionTOP {}
