/* (c) https://github.com/MontiCore/monticore */
package de.monticore.tf.ruletranslation;

import com.google.common.collect.Lists;
import de.monticore.ast.ASTNode;
import de.monticore.ast.Comment;
import de.monticore.expressions.expressionsbasis.ExpressionsBasisMill;
import de.monticore.expressions.expressionsbasis._ast.ASTExpression;
import de.monticore.literals.mccommonliterals._ast.ASTBooleanLiteral;
import de.monticore.literals.mccommonliterals._ast.ASTStringLiteral;
import de.monticore.literals.mcjavaliterals._ast.ASTIntLiteral;
import de.monticore.tf.odrules.HierarchyHelper;
import de.monticore.types.mcbasictypes._ast.ASTConstantsMCBasicTypes;
import de.monticore.types.mcbasictypes._ast.ASTMCPrimitiveType;
import de.monticore.types.mcbasictypes._ast.ASTMCQualifiedName;
import de.monticore.types.mcsimplegenerictypes._ast.ASTMCBasicGenericType;
import de.monticore.umlstereotype._ast.ASTStereoValue;
import de.monticore.umlstereotype._ast.ASTStereotype;
import de.se_rwth.commons.Names;
import de.se_rwth.commons.Splitters;
import de.se_rwth.commons.logging.Log;
import de.monticore.tf.odrules.ODRulesMill;
import de.monticore.tf.odrules._ast.*;
import de.monticore.tf.odrules.util.ODRuleStereotypes;
import de.monticore.tf.odrules.util.Util;
import de.monticore.tf.rule2od.Variable2AttributeMap;
import de.monticore.tf.tfcommons._ast.*;
import de.monticore.tf.tfcommons._visitor.TFCommonsVisitor2;
import de.monticore.tf.ast.*;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;

import static de.se_rwth.commons.StringTransformations.capitalize;
import static de.monticore.tf.ruletranslation.Position.*;

/**
 * Base visitor that translates TF rules into object diagram (OD) based rules.
 */
@SuppressWarnings("unused")
public abstract class Rule2ODVisitor implements TFCommonsVisitor2 {

  // The transformation rule in object diagram syntax generated by this visitor
  protected Rule2ODState state;

  /**
   * Comment denotating, that a statement is assigned a list-child
   */
  public final static Comment LISTCHILD_COMMENT = new Comment("/* INTERNAL: LISTCHILD_ASSIGNMENT */");

  /**
   * Creates a translation visitor with fresh state.
   *
   * @param variable2Attributes mapping from schema variables to attribute metadata
   * @param parents parent map of parsed AST nodes
   */
  public Rule2ODVisitor(Variable2AttributeMap variable2Attributes, Map<ASTNode, ASTNode> parents) {
    super();
    this.state = new Rule2ODState(variable2Attributes,parents);
  }
  
  /**
   * Creates a translation visitor reusing an existing state.
   *
   * @param state existing translation state
   */
  public Rule2ODVisitor(Rule2ODState state){
    this.state = state;
  }


  /**
   * Resolves an object in the generated LHS by its name.
   *
   * @param name object name
   * @return the matching object, or {@code null} if no object exists
   */
  protected @Nullable ASTODObject getLhsObjectByName(@Nonnull String name) {
    for (ASTODObject o : Util.getAllODObjects(state.getLhs())) {
      if (name.equals(o.getName())) {
        return o;
      }
    }
    return null;
  }

  /**
   * Resolves an object in the generated RHS by its name.
   *
   * @param name object name
   * @return the matching object, or {@code null} if no object exists
   */
  protected @Nullable ASTODObject getRhsObjectByName(@Nonnull String name) {
    for (ASTODObject o : Util.getAllODObjects(state.getRhs())) {
      if (name.equals(o.getName())) {
        return o;
      }
    }
    return null;
  }

  /**
   * Adds an object to the generated LHS.
   * If no hierarchy parent exists, the object is added as top-level object,
   * otherwise it is attached as inner link of the current hierarchy parent.
   *
   * @param object object to add
   */
  protected void addObjectToLHS(@Nonnull ASTODObject object) {
    if (state.getHierarchyLHS().isEmpty()) {
      state.getLhs().addODObject(object);
    }
    else {
      ASTODInnerLinkBuilder builder = ODRulesMill.oDInnerLinkBuilder();
      builder.setODObject(object);
      state.getHierarchyLHS().peek().addInnerLinks(builder.build());
    }
  }

  /**
   * Adds an object to the generated RHS.
   * If no hierarchy parent exists, the object is added as top-level object,
   * otherwise it is attached as inner link of the current hierarchy parent.
   *
   * @param object object to add
   */
  protected void addObjectToRHS(@Nonnull ASTODObject object) {
    if (state.getHierarchyRHS().isEmpty()) {
      state.getRhs().addODObject(object);
    }
    else {
      ASTODInnerLinkBuilder builder = ODRulesMill.oDInnerLinkBuilder();
      builder.setODObject(object);
      state.getHierarchyRHS().peek().addInnerLinks(builder.build());
    }
  }

  @Override
  public void visit(ASTTFWhere node) {
    state.getGenRule().setConstraint(node.getConstraint().deepClone());
  }

  @Override
  public void visit(ASTTFAssignments node) {
    for (ASTAssign assign : node.getAssignList()) {
      ASTAssignment assignment = ODRulesMill.assignmentBuilder().uncheckedBuild();
      assignment.setLhs(assign.getVariable());
      assignment.setRhs(assign.getValue().deepClone());
      state.getGenRule().addAssignment(assignment);
    }
  }

  @Override
  public void visit(ASTTFFolding node) {
    for (de.monticore.tf.tfcommons._ast.ASTFoldingSet f : node.getFoldingSetList()) {
      state.getGenRule().addFoldingSet(transformFoldingSet(f));
    }
  }

  @Override
  public void endVisit(ASTTFRule node){
    HierarchyHelper tempHelper = new HierarchyHelper(state.getGenRule());
    for(String key : state.getVariable2Attributes().getV2a().keySet()) {
      String nameForElem = state.getNameGen().getNameForElement(state.getVariable2Attributes().getObject(key));
      boolean isListChild = tempHelper.isListChild(nameForElem);
      String value = nameForElem;
      String attr_value = state.getVariable2Attributes().getAttributeName(key);
      if (state.getVariable2Attributes().isList(key)) {
        attr_value = attr_value.replace("s.", "sList.");
      }
      value += ".get" + capitalize(attr_value).replace(".","().");
      if(!value.endsWith(")")) {
        value += "()";
      }
      if(!value.startsWith("$")){
        value = "m." +  value;
      }
      try {
        ASTAssignment assignment = ODRulesMill.assignmentBuilder().uncheckedBuild();
        assignment.setLhs(key);
        assignment.setRhs(ODRulesMill.parser().parse_StringExpression(value).get());
        if (isListChild) {
          assignment.add_PostComment(LISTCHILD_COMMENT);
        }
        state.getGenRule().getAssignmentList().addFirst(assignment);
      }
      catch (IOException e) {
        Log.error("0xF0901: Invalid Java Expression used in Transformation Rule", e);
      }
    }
  }

  @Override
  public void visit(ASTTFDo node) {
    state.getGenRule().setDoBlock(node.getMCJavaBlock().deepClone());
  }

  /**
   * Transforms a TF folding set into the ODRules representation.
   *
   * @param f source folding set
   * @return transformed folding set
   */
  protected @Nonnull de.monticore.tf.odrules._ast.ASTFoldingSet transformFoldingSet(@Nonnull de.monticore.tf.tfcommons._ast.ASTFoldingSet f) {
    de.monticore.tf.odrules._ast.ASTFoldingSet s = ODRulesMill.foldingSetBuilder().uncheckedBuild();
    s.setObjectNamesList(new ArrayList<>());
    s.getObjectNamesList().addAll(f.getObjectNamesList());
    return s;
  }

  /**
   * Handles one pattern element for the LHS object and applies negative stereotype if required.
   *
   * @param node pattern node from the TF rule
   * @param o_lhs target OD object on the LHS
   */
  protected void handleLHS(@Nonnull IPattern node, @Nonnull ASTODObject o_lhs) {
    doHandle(node, o_lhs);
    if (state.isNegative()) {
      ASTStereotype not = ODRulesMill.stereotypeBuilder().uncheckedBuild();
      ASTStereoValue value = ODRulesMill.stereoValueBuilder().uncheckedBuild();
      value.setName(ODRuleStereotypes.NOT);
      not.addValues(value);

      o_lhs.setStereotype(not);
    }
  }

  /**
   * Handles one pattern element for the RHS object.
   *
   * @param node pattern node from the TF rule
   * @param o_rhs target OD object on the RHS
   */
  protected void handleRHS(@Nonnull IPattern node, @Nonnull ASTODObject o_rhs) {
    doHandle(node, o_rhs);
  }

  /**
   * Initializes object name and type from the given TF pattern node.
   *
   * @param node source TF pattern node
   * @param obj target OD object to initialize
   */
  protected void doHandle(@Nonnull IPattern node, @Nonnull ASTODObject obj) {
    obj.setName(state.getNameGen().getNameForElement(node, state.getParents()));
    List<String> qType =
            Splitters.DOT.splitToList(node._getTFElementType().getName());
    ASTMCBasicGenericType type = ODRulesMill.mCBasicGenericTypeBuilder().uncheckedBuild();
    type.setNameList(qType);
    obj.setType(type);
  }

  /**
   * Resolves and marks a list element on LHS with list metadata.
   *
   * @param node list wrapper node
   * @param listElement element contained in the list
   */
  protected void handleListLHS(@Nonnull IList node, @Nonnull ITFObject listElement) {
    String objectName = state.getNameGen().getNameForElement(listElement, node);
    ASTODObject object = getLhsObjectByName(objectName);
    doHandleList(node, object);
  }

  /**
   * Resolves and marks a list element on RHS with list metadata.
   *
   * @param node list wrapper node
   * @param listElement element contained in the list
   */
  protected void handleListRHS(@Nonnull IList node, @Nonnull ITFObject listElement) {
    String objectName = state.getNameGen().getNameForElement(listElement, node);
    ASTODObject object = getRhsObjectByName(objectName);
    doHandleList(node, object);
  }

  /**
   * Applies list-specific naming and stereotypes to an OD object.
   *
   * @param node list wrapper node
   * @param object OD object to mark as list object; may be {@code null}
   */
  protected void doHandleList(@Nonnull IList node, @Nullable ASTODObject object) {
    if (object == null) {
      return;
    }
    if (node.isPresentSchemaVarName()) {
      object.setName(node.getSchemaVarName());
    }
    ASTStereotype list = ODRulesMill.stereotypeBuilder().uncheckedBuild();
    ASTStereoValue value = ODRulesMill.stereoValueBuilder().uncheckedBuild();
    value.setName(ODRuleStereotypes.LIST);
    list.addValues(value);

    object.setStereotype(list);
  }

  /**
   * Creates an ASTODObject for the given list node
   * and puts it on the hierarchy stack.
   *
   * @param node the list node
   */
  protected void handleList(@Nonnull IList node) {
    ASTODObject objectLhs = ODRulesMill.oDObjectBuilder().uncheckedBuild();
    ASTODObject objectRhs = ODRulesMill.oDObjectBuilder().uncheckedBuild();

    String objectName = state.getNameGen().getNameForElement(node);
    objectLhs.setName(objectName);
    objectRhs.setName(objectName);

    // set stereotype to <<list>>
    ASTStereotype list = ODRulesMill.stereotypeBuilder().uncheckedBuild();
    ASTStereoValue value = ODRulesMill.stereoValueBuilder().uncheckedBuild();
    value.setName(ODRuleStereotypes.LIST);
    list.addValues(value);
    objectLhs.setStereotype(list);
    objectRhs.setStereotype(list);

    // set type to IList
    List<String> qType = Splitters.DOT.splitToList("de.monticore.tf.ast.IList");
    ASTMCBasicGenericType type = ODRulesMill.mCBasicGenericTypeBuilder().uncheckedBuild();
    type.setNameList(qType);
    objectLhs.setType(type);
    objectRhs.setType(type);

    addObjectToLHS(objectLhs);
    state.getHierarchyLHS().push(objectLhs);
    addObjectToRHS(objectRhs);
    state.getHierarchyRHS().push(objectRhs);
  }

  /**
   * Creates an ASTODObject for the given optional node
   * and puts it on the hierarchy stack.
   *
   * @param node the optional node
   */
  protected void handleOpt(@Nonnull IOptional node) {
    ASTODObject objectLhs = ODRulesMill.oDObjectBuilder().uncheckedBuild();
    ASTODObject objectRhs = ODRulesMill.oDObjectBuilder().uncheckedBuild();

    String objectName = state.getNameGen().getNameForElement(node);
    objectLhs.setName(objectName);
    objectRhs.setName(objectName);

    // set stereotype to <<optional>>
    ASTStereotype opt = ODRulesMill.stereotypeBuilder().uncheckedBuild();
    ASTStereoValue value = ODRulesMill.stereoValueBuilder().uncheckedBuild();
    value.setName(ODRuleStereotypes.OPTIONAL);
    opt.addValues(value);
    objectLhs.setStereotype(opt);
    objectRhs.setStereotype(opt);

    // set type to IOptional
    List<String> qType = Splitters.DOT.splitToList("de.monticore.tf.ast.IOptional");
    ASTMCBasicGenericType type = ODRulesMill.mCBasicGenericTypeBuilder().uncheckedBuild();
    type.setNameList(qType);
    objectLhs.setType(type);
    objectRhs.setType(type);

    addObjectToLHS(objectLhs);
    state.getHierarchyLHS().push(objectLhs);
    addObjectToRHS(objectRhs);
    state.getHierarchyRHS().push(objectRhs);
  }

  /**
   * Checks whether the current traversal position contributes to the left-hand side.
   *
   * @return {@code true} if current visitor position affects the LHS
   */
  protected boolean isOnLHS() {
    return (state.getPosition().equals(LHS) || state.getPosition().equals(BOTH));
  }

  /**
   * Checks whether the current traversal position contributes to the right-hand side.
   *
   * @return {@code true} if current visitor position affects the RHS
   */
  protected boolean isOnRHS() {
    return (state.getPosition().equals(RHS) || state.getPosition().equals(BOTH));
  }

  /**
   * Creates an expression from a qualified name.
   * If parsing fails, returns an empty name-expression node.
   *
   * @param parts qualified-name parts
   * @return parsed expression or fallback expression node
   */
  protected @Nonnull ASTExpression createQualifiedNameExpression(@Nonnull List<String> parts) {
    try {
      Optional<ASTExpression> exp = ODRulesMill.parser()
          .parse_StringExpression(Names.constructQualifiedName(parts));
      if (exp.isPresent()) {
        return exp.get();
      }
      else {
        Log.error(
            "0xF0006: " + Names.constructQualifiedName(parts) + " cannot be treated as an expression");
        return ODRulesMill.nameExpressionBuilder().uncheckedBuild();
      }
    }
    catch (IOException e) {
      Log.error(
          "0xF0004: " + Names.constructQualifiedName(parts) + " cannot be treated as an expression");
      return ODRulesMill.nameExpressionBuilder().uncheckedBuild();
    }
  }

  /**
   * Resolves wrappers such as replacements/lists/optionals to the effective TF object.
   *
   * @param child wrapped element
   * @param repSide accessor selecting the LHS/RHS side of replacements
   * @return effective object represented by the element
   */
  protected @Nonnull ITFObject getElementAsObject(@Nonnull ITFElement child, @Nonnull Function<IReplacement, ITFElement> repSide) {
    // replacements do represent an element themself, instead they refer to a LHS and RHS
    // in order to create links, we need to get the actual element of the optional
    if (child instanceof IReplacement) {
      return getElementAsObject(repSide.apply((IReplacement) child), repSide);
    } else {
      // optionals & lists only group elements, they do not represent elements themselves.
      // in order to create links, we need to get the actual element of the optional
      ITFElement elem = child.getTFElement();
      if (elem == child) // Only patterns return themselves as their element
        return (ITFObject) elem;
      return getElementAsObject(elem, repSide);
    }
  }

  /**
   * Creates a composition link for the LHS side.
   *
   * @param parent parent object of the composition
   * @param child referenced child element
   * @param roleName association role name
   * @param genericType generic type metadata
   * @param attrIsIterated whether the attribute is iterated
   * @param attrIsOptional whether the attribute is optional
   * @return generated LHS composition link
   */
  protected @Nonnull ASTODLink createLHSComposition(@Nonnull ITFObject parent, @Nonnull ITFElement child, @Nonnull String roleName, @Nonnull String genericType, boolean attrIsIterated, boolean attrIsOptional) {
    ITFObject component = getElementAsObject(child, IReplacement::getLhs);
    return createLink(parent, roleName, genericType, component, attrIsIterated, attrIsOptional);
  }

  /**
   * Creates a composition link for the RHS side.
   *
   * @param parent parent object of the composition
   * @param child referenced child element
   * @param roleName association role name
   * @param genericType generic type metadata
   * @param attrIsIterated whether the attribute is iterated
   * @param attrIsOptional whether the attribute is optional
   * @return generated RHS composition link
   */
  protected @Nonnull ASTODLink createRHSComposition(@Nonnull ITFObject parent, @Nonnull ITFElement child, @Nonnull String roleName, @Nonnull String genericType,
                                           boolean attrIsIterated, boolean attrIsOptional) {
    ITFObject component = getElementAsObject(child, IReplacement::getRhs);
    return createLink(parent, roleName, genericType, component, attrIsIterated, attrIsOptional);
  }

  /**
   * Unwraps list/optional wrapper elements and returns the actual object element.
   *
   * @param component wrapped or direct object
   * @return unwrapped object element
   */
  protected @Nonnull ITFObject getActualElement(@Nonnull ITFObject component) {
    if (component instanceof IOptional || component instanceof  IList) {
      component = (ITFObject) component.getTFElement();
      return getActualElement(component);
    } else {
      return component;
    }
  }

  /**
   * Creates a link and adds the {@code insertType} stereotype metadata.
   *
   * @param parent parent object of the composition
   * @param roleName association role name
   * @param genericType generic type metadata
   * @param component referenced component object
   * @param insertType insertion strategy identifier
   * @param attrIsIterated whether the attribute is iterated
   * @param attrIsOptional whether the attribute is optional
   * @return generated link with insert-type metadata
   */
  protected @Nonnull ASTODLink createLinkInsertAt(@Nonnull ITFObject parent, @Nonnull String roleName, @Nonnull String genericType, @Nonnull ITFObject component, @Nonnull String insertType, boolean attrIsIterated, boolean attrIsOptional) {
    ASTODLink composition = createLink(parent, roleName, genericType, component, attrIsIterated, attrIsOptional);
    ASTStereotype stereotype = composition.getStereotype();
    ASTStereoValue stereoValueType = ODRulesMill.stereoValueBuilder().uncheckedBuild();
    stereoValueType.setName("insertType");
    stereoValueType.setContent(insertType);
    stereotype.addValues(stereoValueType);
    return composition;
  }
  /**
   * Creates a link with {@code insertType} and concrete {@code insertAt} metadata.
   *
   * @param parent parent object of the composition
   * @param roleName association role name
   * @param genericType generic type metadata
   * @param component referenced component object
   * @param insertType insertion strategy identifier
   * @param insertAt anchor object for insertion
   * @param attrIsIterated whether the attribute is iterated
   * @param attrIsOptional whether the attribute is optional
   * @return generated link with insert-type and insert-at metadata
   */
  protected @Nonnull ASTODLink createLinkInsertAt(@Nonnull ITFObject parent, @Nonnull String roleName, @Nonnull String genericType, @Nonnull ITFObject component, @Nonnull String insertType,
                                         @Nonnull ITFObject insertAt, boolean attrIsIterated, boolean attrIsOptional) {
    ASTODLink composition = createLinkInsertAt(parent, roleName, genericType, component, insertType, attrIsIterated, attrIsOptional);
    ASTStereoValue stereoValueAt = ODRulesMill.stereoValueBuilder().uncheckedBuild();
    stereoValueAt.setName("insertAt");
    stereoValueAt.setContent(state.getNameGen().getNameForElement(getActualElement(insertAt)));
    composition.getStereotype().addValues(stereoValueAt);
    return composition;
  }

  /**
   * Creates an OD composition link with references, cardinality and optional generic metadata.
   *
   * @param parent parent object of the composition
   * @param roleName association role name
   * @param genericType generic type metadata
   * @param component referenced component object
   * @param attrIsIterated whether the attribute is iterated
   * @param attrIsOptional whether the attribute is optional
   * @return generated OD link
   */
  protected @Nonnull ASTODLink createLink(@Nonnull ITFObject parent, @Nonnull String roleName, @Nonnull String genericType,
                                 @Nonnull ITFObject component, boolean attrIsIterated, boolean attrIsOptional){
    ASTODLink composition = ODRulesMill.oDLinkBuilder().uncheckedBuild();
    composition.setRightRole(roleName);
    List<String> lhs_compositeName = Splitters.DOT.splitToList(state.getNameGen().getNameForElement(parent, state.getParents()));
    ASTMCQualifiedName lhs_compositeQName = ODRulesMill.mCQualifiedNameBuilder().uncheckedBuild();
    lhs_compositeQName.setPartsList(lhs_compositeName);
    composition.addLeftReferenceName(lhs_compositeQName);
    List<String> lhs_componentName =  Splitters.DOT.splitToList(state.getNameGen().getNameForElement(component,state.getParents()));
    ASTMCQualifiedName lhs_componentQName = ODRulesMill.mCQualifiedNameBuilder().uncheckedBuild();
    lhs_componentQName.setPartsList(lhs_componentName);
    composition.addRightReferenceName(lhs_componentQName);
    ASTCardinality cardinality = ODRulesMill.cardinalityBuilder().uncheckedBuild();
    cardinality.setOptional(attrIsOptional && !attrIsIterated);
    cardinality.setOne(!attrIsOptional && !attrIsIterated);
    cardinality.setOneToMany(!attrIsOptional && attrIsIterated);
    cardinality.setMany(attrIsOptional && attrIsIterated);
    composition.setAttributeCardinality(cardinality);
    if(!genericType.isEmpty()) {
      ASTStereotype stereotype = ODRulesMill.stereotypeBuilder().uncheckedBuild();
      ASTStereoValue stereoValueType = ODRulesMill.stereoValueBuilder().uncheckedBuild();
      stereoValueType.setName("genericType");
      stereoValueType.setContent(genericType);
      stereotype.addValues(stereoValueType);
      composition.setStereotype(stereotype);
    }
    return composition;
  }

  /**
   * Creates a boolean-typed OD attribute and assigns the provided value.
   *
   * @param name attribute name
   * @param value attribute value expression
   * @param isOptional whether cardinality is optional
   * @return generated boolean attribute
   */
  protected @Nonnull ASTODAttribute createAttributeForBoolean(@Nonnull String name, @Nonnull ASTExpression value, boolean isOptional) {
    ASTODAttribute attribute = ODRulesMill.oDAttributeBuilder().uncheckedBuild();
    attribute.setName(name);
    ASTMCPrimitiveType primitiveType = ODRulesMill.mCPrimitiveTypeBuilder().uncheckedBuild();
    primitiveType.setPrimitive(ASTConstantsMCBasicTypes.BOOLEAN);
    attribute.setMCType(primitiveType);
    attribute.setSingleValue(value);
    attribute.setAttributeCardinality(ODRulesMill.cardinalityBuilder().uncheckedBuild());
    attribute.getAttributeCardinality().setOptional(isOptional);
    attribute.getAttributeCardinality().setOne(!isOptional);
    return attribute;
  }

  /**
   * Creates a boolean literal expression from the parser constant.
   *
   * @param astConstant parser constant representing a boolean value
   * @return generated boolean literal expression
   */
  protected @Nonnull ASTExpression createExpressionForBoolean(int astConstant) {
    ASTBooleanLiteral booleanLiteral = ODRulesMill.booleanLiteralBuilder().uncheckedBuild();
    booleanLiteral.setSource(astConstant);
    return ExpressionsBasisMill.literalExpressionBuilder().setLiteral(booleanLiteral).build();
  }
  
  /**
   * Creates an int literal expression from the parser constant.
   *
   * @param astConstant parser constant representing an int value
   * @return generated int literal expression
   */
  protected @Nonnull ASTExpression createExpressionForInt(int astConstant) {
    ASTIntLiteral intLiteral = ODRulesMill.intLiteralBuilder().uncheckedBuild();
    intLiteral.setSource(""+astConstant);
    return ExpressionsBasisMill.literalExpressionBuilder().setLiteral(intLiteral).build();
  }

  /**
   * Creates a string-typed OD attribute.
   *
   * @param name attribute name
   * @param isOptional whether cardinality is optional
   * @return generated string attribute
   */
  protected @Nonnull ASTODAttribute createAttributeForString(@Nonnull String name, boolean isOptional) {
    ASTODAttribute attribute = ODRulesMill.oDAttributeBuilder().uncheckedBuild();
    ASTMCBasicGenericType type = ODRulesMill.mCBasicGenericTypeBuilder().uncheckedBuild();
    type.setNameList(Splitters.DOT.splitToList("String"));
    attribute.setMCType(type);
    attribute.setName(name);
    attribute.setAttributeCardinality(ODRulesMill.cardinalityBuilder().uncheckedBuild());
    attribute.getAttributeCardinality().setOptional(isOptional);
    attribute.getAttributeCardinality().setOne(!isOptional);
    return attribute;
  }

  /**
   * Creates a string literal expression from the given raw value.
   *
   * @param variableName literal source content
   * @return generated string literal expression
   */
  protected @Nonnull ASTExpression createPrimaryExpressionForString(@Nonnull String variableName) {
    ASTStringLiteral stringLiteral =  ODRulesMill.stringLiteralBuilder().uncheckedBuild();
    stringLiteral.setSource(variableName);
    return ExpressionsBasisMill.literalExpressionBuilder().setLiteral(stringLiteral).build();
  }

  /**
   * Creates a qualified-name expression and assigns it as attribute value.
   *
   * @param attribute target attribute
   * @param parts qualified-name parts
   */
  protected void createQualifiedNameExpressionAsAttributeValue(@Nonnull ASTODAttribute attribute,
      @Nonnull String... parts) {
    List<String> stringList = Lists.newArrayList(parts);
    ASTExpression qualifiedNameExpression = createQualifiedNameExpression(stringList);
    attribute.setSingleValue(qualifiedNameExpression);
  }
}
