/* generated by template symboltable.serialization.ArtifactScopeSerializer*/

package de.monticore.types.serialization;

import java.util.List;

import com.google.common.collect.ImmutableList;

import de.monticore.symboltable.ArtifactScope;
import de.monticore.symboltable.MutableScope;
import de.monticore.symboltable.Symbol;
import de.monticore.symboltable.serializing.ArtifactScopeSerialization;
import de.monticore.symboltable.serializing.CommonArtifactScopeSerializer;
import de.monticore.symboltable.serializing.DelegatingSerializer;
import de.monticore.symboltable.serializing.ISerialization;

public class TypesSerializer extends CommonArtifactScopeSerializer {
  
  public TypesSerializer() {
    super();
    List<ISerialization<?>> serializers = ImmutableList.of(
        new ASTMCQualifiedTypeSerializer()
        );
    
    DelegatingSerializer delegatingSerializer = new DelegatingSerializer(serializers);
    
    for (ISerialization<?> serializer : serializers) {
      gson.registerTypeAdapter(serializer.getSerializedClass(), serializer);
    }
  }
}
