/* (c) https://github.com/MontiCore/monticore */
java {
  withJavadocJar()
  withSourcesJar()
}

dependencies {
  implementation "de.se_rwth.commons:se-commons-logging:$se_commons_version"
  implementation project(':monticore-runtime')
  implementation project(':monticore-grammar')
  implementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
  runtimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit_version"
}
