<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ActionAutomaton" nsURI="http://ActionAutomaton/1.0" nsPrefix="ActionAutomaton">
  <eClassifiers xsi:type="ecore:EEnum"/>
  <eClassifiers xsi:type="ecore:EClass" name="ASTAutomaton">
    <eSuperTypes href="FlatAutomaton.ecore#//ASTAutomaton"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Counters" unique="false" upperBound="-1" eType="//ASTCounter" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="States" unique="false" upperBound="-1" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="FlatAutomaton.ecore#//ASTState"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Transitions" unique="false" upperBound="-1" containment="true" resolveProxies="false">
      <eType xsi:type="ecore:EClass" href="FlatAutomaton.ecore#//ASTTransition"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ASTCounter">
    <eSuperTypes href="ASTENode.ecore#//ENode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Names" upperBound="-1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
