/* (c) https://github.com/MontiCore/monticore */

plugins {
  id "java-library"
  id "de.monticore.generator" // MontiCore Plugin
}

description = 'MontiCore: EMF Grammar'

sonarqube {
  skipProject = true
}

dependencies {
    api project(':monticore-runtime')
    api project(':monticore-runtime-emf')
    implementation "com.google.guava:guava:$guava_version"
    implementation "org.apache.commons:commons-lang3:$commons_lang3_version"
    implementation 'org.eclipse.emf:org.eclipse.emf.ecore:2.15.0'
    implementation 'org.eclipse.emf:org.eclipse.emf.ecore.xmi:2.15.0'
    implementation 'org.eclipse.emf:org.eclipse.emf.common:2.15.0'

    testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
    testImplementation "org.junit.jupiter:junit-jupiter-params:$junit_version"
    testImplementation "org.junit.jupiter:junit-jupiter-engine:$junit_version"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:$junit_version"
    testRuntimeOnly project(":monticore-libraries:javagen-runtime")
    testImplementation 'org.apache.groovy:groovy:4.0.2'
    testImplementation testFixtures(project(':monticore-runtime'))
}

def srcDir = layout.buildDirectory.dir("main/java")
def srcResourcesDir = layout.buildDirectory.dir("main/resources")
def testDir = layout.buildDirectory.dir("test/java")

tasks.register('copySrc', Copy) {
  from "${project(':monticore-grammar').projectDir}/src/main/java"
  into srcDir
}

tasks.register('copySrcResources', Copy) {
  from "${project(':monticore-grammar').projectDir}/src/main/resources"
  into srcResourcesDir
}

tasks.register('copyTest', Copy) {
  from "${project(':monticore-grammar').projectDir}/src/test/java"
  into testDir
}

tasks.register('copyTestResources', Copy) {
  from "${project(':monticore-grammar').projectDir}/src/test/resources"
  into layout.buildDirectory.dir("test/resources")
}

def grammarDir = "${project(':monticore-grammar').projectDir}/src/main/grammars"

sourceSets {
  main.java.srcDirs = [ srcDir]
  main.resources.srcDirs = [ srcResourcesDir]
  test.java.srcDirs += [ testDir]
  test.grammars.srcDirs = ["${project(':monticore-grammar').projectDir}/src/test/grammars",
                           "${project(':monticore-grammar').projectDir}/src/main/examples"]
}

tasks.register('generate') {}

tasks.named('generateMCGrammars') {
  grammar = file(grammarDir)
  script = "de/monticore/monticore_emf.groovy"
  modelPath = "${project(':monticore-grammar').projectDir}/src/main/grammars"
  handWrittenCodeDir = files(srcDir)
  genINT = true
  dependsOn(copySrc, copyTest, copyTestResources)
}

generateTestMCGrammars {
  script = "de/monticore/monticore_emf.groovy"
  modelPath = files("$grammarDir", "${project(':monticore-grammar').projectDir}/src/test/grammars", "${project(':monticore-grammar').projectDir}/src/main/examples")
  handWrittenCodeDir = files(srcDir, testDir)
  genINT = true
  dependsOn(copySrc, copyTest, copyTestResources)
}

test {
  useJUnitPlatform()
  exclude '**/CommentsOnASTTest.class'
  exclude '**/SwitchStatementValidTest.class'
  exclude '**/GrammarInheritanceCycleTest.class'
  exclude '**/GrammarNameEqualsFileNameTest.class'
  exclude '**/MCGrammarParserTest.class'
  exclude '**/MCGrammarPrettyPrinterTest.class'
  exclude '**/SynthesizeSymTypeFromMCBasicTypesTest.class'
  exclude '**/SynthesizeSymTypeFromMCCollectionTypesTest.class'
  exclude '**/SynthesizeSymTypeFromMCSimpleGenericTypesTest.class'
  exclude '**/SynthesizeSymTypeFromMCFullGenericTypesTest.class'
  exclude '**/SynthesizeSymTypeFromMCArrayTypesTest.class'
  exclude '**/MCType2SymTypeExpressionTest.class'
  exclude '**/ComponentTypeSymbolDeSerTest.class'
}


compileJava.dependsOn (tasks.named("copySrc"))
compileJava.dependsOn (tasks.named("copySrcResources"))
processResources.dependsOn (tasks.named("copySrcResources"))
sourcesJar.dependsOn (tasks.named("copySrcResources"))
compileTestJava.dependsOn (tasks.named("copyTest"))
compileTestJava.dependsOn (tasks.named("copyTestResources"))
processTestResources.dependsOn (tasks.named("copyTestResources"))
