/* (c) https://github.com/MontiCore/monticore */

/* generated from model null*/
/* generated by template symboltable.ModelingLanguage*/




package mc.embedding.transitive.transhost._symboltable;

public class TransHostLanguage extends TransHostLanguageTOP {

  public final static String FILE_ENDING = "transhost";
  public TransHostLanguage() {
    super("Trans Host Language", FILE_ENDING);
  }

  @Override
  public TransHostModelLoader getModelLoader() {
    return (TransHostModelLoader) super.getModelLoader();
  }

  @Override
  protected TransHostModelLoader provideModelLoader() {
    return new TransHostModelLoader(this);
  }
}
