/* (c) https://github.com/MontiCore/monticore */

package mc.feature.hwc.statechartdsl._ast;

import mc.feature.hwc.statechartdsl._ast.ASTStatechartDSLNodeTOP;

/* generated by template ast.ASTNodeBase*/

/**
 * Interface for all AST nodes of the StatechartDSL language.
 */
public interface ASTStatechartDSLNode extends ASTStatechartDSLNodeTOP {
  
  default String foo() {
    return getClass().getSimpleName();
  }
  
}
