/* generated from model InterpreterTestLang */
/* generated by template cd2java.Class*/

/* (c) https://github.com/MontiCore/monticore */

/* Hookpoint: ClassContent:addComment */

/* generated by template cd2java.Package*/
package de.monticore.tests.interpretertestlang._symboltable;

import de.monticore.symboltable.ImportStatement;
import de.monticore.tests.interpretertestlang._ast.ASTInterpreterInput;
import de.monticore.types.mcbasictypes._ast.ASTMCImportStatement;

import java.util.ArrayList;
import java.util.List;

public class InterpreterTestLangScopesGenitor
    extends InterpreterTestLangScopesGenitorTOP {

  @Override
  public IInterpreterTestLangArtifactScope createFromAST(
      ASTInterpreterInput node
  ) {
    IInterpreterTestLangArtifactScope result = super.createFromAST(node);
    result.setName("TestA");
    List<ImportStatement> imports = new ArrayList<>();
    for (ASTMCImportStatement importStmt : node.getMCImportStatementList()) {
      imports.add(
          new ImportStatement(importStmt.getQName(), importStmt.isStar())
      );
    }
    result.setImportsList(imports);
    return result;
  }

}


