/* (c) https://github.com/MontiCore/monticore */
buildscript {
  dependencies {
    classpath "de.se_rwth.commons:se-commons-gradle:$se_commons_version"
  }
}
plugins {
  id 'java-library'
  id 'java-gradle-plugin'
  id 'maven-publish'
}

configurations {
  // The plugin's footprint is fairly small, as it loads the generator itself into a "mcTool" configuration
  // to avoid polluting Gradle's classpath
  mcTool
}

dependencies {
  implementation gradleApi()
  implementation "de.se_rwth.commons:se-commons-gradle:$se_gradle_version" // use current version of the gradle-dependency
  implementation "de.monticore:monticore-runtime:$previous_mc_version" // Required due to json -> substitute this to remove the runtime from the gradle projects classpath
  mcTool project(":") // depend on the generator subproject

  testImplementation gradleTestKit()
}

sourceSets {
  main.compileClasspath += configurations.mcTool
  test.compileClasspath += configurations.mcTool
}


gradlePlugin.plugins {
  // New version of our plugin (supporting incremental builds)
  monticoreGenerator {
    id = "de.monticore.generator"
    implementationClass = 'de.monticore.gradle.MCGeneratorPlugin'
  }
  monticoreGeneratorWithTR {
    id = "de.monticore.generator-withtr"
    implementationClass = 'de.monticore.gradle.MCGeneratorWithTRPlugin'
  }
}

tasks.register("buildInfo", de.monticore.gradle.common.MCBuildInfoTask) {
  // With an input property ensuring UP-TO-DATE checks consider the version property
  version = project.version
}

processResources.dependsOn("buildInfo")

tasks.named("test") {
  // The test uses the output of the generator's shadowJar task
  dependsOn(project(":").tasks.shadowJar)
  inputs.files(project(":").tasks.shadowJar)

  // For the MontiVerse
  systemProperty "maven.repo.local", System.getProperty("maven.repo.local")
  systemProperty "useLocalRepo", findProperty("useLocalRepo")
}
publishing {
  // The gradle-plugin plugin adds&configures a publication automatically.
  // But we have to specify the repositories explicitly (again)
  // allprojects in the generator project does not appear to work for this.
  repositories {
    maven {
      name = "SE-Nexus"
      credentials.username = mavenUser
      credentials.password = mavenPassword
      def releasesRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/monticore-releases/"
      def snapshotsRepoUrl = "https://nexus.se.rwth-aachen.de/content/repositories/monticore-snapshots/"
      url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
    }
    // Also publish to the github repository, if run on a github action
    if (System.getenv("GITHUB_REPOSITORY") != null) {
      maven {
        name = "GitHubPackages"
        url = "https://maven.pkg.github.com/" + System.getenv("GITHUB_REPOSITORY")
        credentials {
          username = System.getenv("GITHUB_ACTOR")
          password = System.getenv("GITHUB_TOKEN")
        }
      }
    }
  }
}
