/* generated from model BasicSymbols */
/* generated by template core.Interface*/

/* (c) https://github.com/MontiCore/monticore */
package de.monticore.visitor;


import de.monticore.ast.ASTNode;
import de.monticore.symboltable.IScope;
import de.monticore.symboltable.ISymbol;

public interface ITraverser {

  // ASTNode
  // void handle(ASTNode node);

  void visit(ASTNode node);

  // void traverse (ASTNode node);

  void endVisit(ASTNode node);

  // ISymbol
  // void handle(ISymbol symbol);

  void visit(ISymbol symbol);

  // void traverse (ISymbol symbol);

  void endVisit(ISymbol symbol);

  // IScope
  // void handle(IScope scope);

  void visit(IScope scope);

  // void traverse (IScope scope);

  void endVisit(IScope scope);

}
