/* generated from model BasicSymbols */
/* generated by template core.Interface*/

/* (c) https://github.com/MontiCore/monticore */
package de.monticore.visitor;


import de.monticore.ast.ASTNode;
import de.monticore.symboltable.IScope;
import de.monticore.symboltable.ISymbol;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public interface ITraverser {

  default void add4IVisitor (IVisitor iVisitor) {}

  default List<IVisitor> getIVisitorList () {
    return new ArrayList<>();
  }

  default Optional<IHandler> getIHandler ()  {
    return Optional.empty();
  }

  default void setIHandler (IHandler iHandler)  {
  }

  // ASTNode
  default void handle(ASTNode node) {
    if (getIHandler().isPresent()) {
      getIHandler().get().handle(node);
    } else {
      visit(node);
      // no traverse() for abstract classes, interfaces and enums, only concrete classes are traversed
      endVisit(node);
    }
  }

  default void visit(ASTNode node) {
    getIVisitorList().forEach(v -> v.visit(node));
  }

  default void endVisit(ASTNode node) {
    getIVisitorList().forEach(v -> v.endVisit(node));
  }

  // ISymbol
  default void handle(ISymbol symbol) {
    if (getIHandler().isPresent()) {
      getIHandler().get().handle(symbol);
    } else {
      visit(symbol);
      // no traverse() for abstract classes, interfaces and enums, only concrete classes are traversed
      endVisit(symbol);
    }
  }

  default void visit(ISymbol symbol){
    getIVisitorList().forEach(v -> v.visit(symbol));
  }

  default void endVisit(ISymbol symbol){
    getIVisitorList().forEach(v -> v.endVisit(symbol));
  }

  // IScope
  default void handle(IScope scope) {
    if (getIHandler().isPresent()) {
      getIHandler().get().handle(scope);
    } else {
      visit(scope);
      // no traverse() for abstract classes, interfaces and enums, only concrete classes are traversed
      endVisit(scope);
    }
  }

  default void visit(IScope scope){
    getIVisitorList().forEach(v -> v.visit(scope));
  }

  default void endVisit(IScope scope){
    getIVisitorList().forEach(v -> v.endVisit(scope));
  }
}
