/* generated from model BasicSymbols */
/* generated by template core.Interface*/

/* (c) https://github.com/MontiCore/monticore */
package de.monticore.visitor;


import de.monticore.ast.ASTNode;
import de.monticore.symboltable.IScope;
import de.monticore.symboltable.ISymbol;

public interface IVisitor2 {

  default void endVisit(ASTNode node) {
  }

  default void visit(ASTNode node) {
  }

  default void visit(ISymbol symbol) {
  }

  default void endVisit(ISymbol symbol) {
  }

  default void visit(IScope scope) {
  }

  default void endVisit(IScope scope) {
  }

}
