package de.monticore.emf._ast;

public class ASTConstantsASTENode extends Object {
  
  public static final String LANGUAGE = "de.monticore.emf.ASTENode";
  
  /* generated by mc.codegen.ast.constants.ASTConsts */
  public static final int DEFAULT = 0;
  
  /** Constructs a new ASTConstantsASTENode. */
  public ASTConstantsASTENode() {
  }
  
}
