/* (c) https://github.com/MontiCore/monticore */
plugins {
  id "java"
  id "jacoco"
}

configurations {
  testsImplementation.extendsFrom(testImplementation)
}

dependencies {
  testRuntimeOnly project(':monticore-libraries:stream-symbols')
  testImplementation project(':monticore-grammar')
  testImplementation 'de.se_rwth.commons:se-commons-logging:' + se_commons_version
  testImplementation 'de.se_rwth.commons:se-commons-utilities:' + se_commons_version
  testImplementation "org.junit.jupiter:junit-jupiter-api:$junit_version"
  testImplementation "org.junit.vintage:junit-vintage-engine:$junit_version"
  testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junit_version"
}

test {
  useJUnitPlatform()
}

description = 'MontiCore: Stream Symbols'
