# (c) https://github.com/MontiCore/monticore
name: "Trigger the MontiVerse (workflow-call)"

on:
  workflow_call:
    inputs:
      project:
        description: 'The (internal) name for this project, as defined within the MontiVerse job'
        type: string
        required: true
      branch:
        description: 'The branch to use for building the MontiVerse, such as head.ref'
        type: string
        required: true
      repo:
        description: 'The project path to use for building the MontiVerse, such as head.repo.full_name'
        type: string
        required: true
    secrets:
      MONTIVERSE_TRIGGER_TOKEN:
        required: true
      MONTIVERSE_ACCESS_TOKEN:
        required: true


jobs:
  # Run the MontiVerse pipeline (tests this change on a suite of projects)
  # The MontiVerse is a suite of projects, which are not build & tested with the given changes on a branch
  trigger-montiverse:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger MontiVerse
        uses: digital-blueprint/gitlab-pipeline-trigger-action@c81ead300bf664f76245d816268c4a1b4bed2604 # @v1.2.0
        with:
          host: 'git.rwth-aachen.de'
          trigger_token: ${{ secrets.MONTIVERSE_TRIGGER_TOKEN }}
          access_token: ${{ secrets.MONTIVERSE_ACCESS_TOKEN }}  # Access is required to show the status
          id: '91803'  # montiverseci project id
          ref: 'main'
          # We should include the entire git path here instead of just a branch due to PRs from external projects, etc.
          variables: '{"${{inputs.project}}_BRANCH":"${{inputs.branch}}", "${{inputs.project}}_PROJECT":"${{ inputs.repo }}"}'