# (c) https://github.com/MontiCore/monticore
name: Publish a Release

on:
  release:
    types:
      - created

permissions:
  contents: read
  packages: write

env:
  GRADLE_VERSION: 8.14.4 # Gradle version used
  JAVA_VERSION: 21 # Java version used
  GRADLE_CLI_OPTS: "-Pci" # CLI option passed to Gradle

jobs:
  # Deploy the current tag as a release
  deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}
      - name: Prepare Gradle for DeployMC
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{env.GRADLE_VERSION}}
      - name: Gradle DeployMC
        # pass the tag as the version property (${{ github.ref_name }})
        run: gradle deployMC ${{env.GRADLE_CLI_OPTS}} -PmavenPassword=${{secrets.SE_NEXUS_PASSWORD}} -PmavenUser=${{secrets.SE_NEXUS_USER}} -PgenEMF=true -PgenTR=true -PgenTagging=true -Pversion=${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # TODO: Create and publish the monticore.tar.gz
      # TODO: Create PRs in the various downstream projects to update the version & prepare releases
